## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'Day_001_HW.ipynb',
 'Day_002_HW.ipynb',
 'Day_003_HW.ipynb',
 'Day_004_HW.ipynb',
 'Part01',
 'README.md']

In [7]:
# 設定 data_path
dir_data = './/Part01'

In [8]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: .//Part01\application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [12]:
print('No. of rows')
print(len(app_train))
print('No. of columns')
print(len(app_train.columns))

No. of rows
307511
No. of columns
122

#### 列出所有欄位

In [13]:
app_train.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 截取部分資料

In [14]:
app_train.sample(4000)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
239635,377496,0,Cash loans,F,N,Y,0,90000.0,278712.0,9031.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
118753,237708,1,Revolving loans,M,N,N,0,135000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0
123098,242745,0,Cash loans,F,N,Y,0,157500.0,630000.0,36166.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
59879,169418,0,Revolving loans,M,Y,Y,1,131706.0,135000.0,6750.0,...,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
67765,178588,0,Cash loans,M,Y,Y,0,72000.0,808650.0,26217.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
296193,443155,1,Cash loans,F,N,Y,0,112500.0,450346.5,23710.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
133352,254664,0,Revolving loans,F,Y,Y,0,90000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
170723,297856,0,Cash loans,F,N,Y,1,45000.0,76500.0,9207.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
127378,247720,0,Cash loans,M,Y,Y,4,225000.0,450000.0,22977.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
137433,259392,0,Cash loans,F,N,N,1,135000.0,675000.0,19737.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
162507,288394,0,Revolving loans,F,Y,N,0,225000.0,675000.0,33750.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
245561,384178,0,Cash loans,F,N,Y,2,117000.0,74628.0,7834.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
227187,363150,0,Cash loans,F,N,N,0,126000.0,906228.0,40045.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
110854,228603,0,Cash loans,F,N,Y,0,288000.0,645903.0,51160.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
135641,257327,0,Cash loans,M,Y,Y,2,157500.0,314100.0,16573.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
197621,329126,0,Cash loans,F,N,Y,2,81000.0,135000.0,13279.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
46660,154050,0,Cash loans,M,N,Y,0,135000.0,521280.0,24286.5,...,1,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
134902,256472,0,Cash loans,F,N,Y,0,32967.0,310671.0,19134.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
230521,367013,0,Cash loans,F,N,Y,0,270000.0,970380.0,28372.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
221273,356322,0,Cash loans,F,N,Y,0,135000.0,942300.0,30528.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
81834,194898,0,Cash loans,F,N,Y,0,135000.0,1288350.0,37800.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
156941,281902,0,Cash loans,M,Y,Y,0,162000.0,1696500.0,70141.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
112830,230877,1,Cash loans,F,N,Y,0,112500.0,369000.0,18076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
137650,259640,0,Cash loans,F,N,Y,0,274500.0,900000.0,26446.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
210185,343575,0,Cash loans,F,N,Y,0,126000.0,675000.0,45292.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
232462,369250,0,Cash loans,F,N,Y,0,67500.0,486459.0,23791.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
9266,110777,0,Cash loans,M,Y,Y,0,103500.0,1218118.5,48438.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
52718,161064,0,Revolving loans,M,N,Y,0,180000.0,360000.0,18000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
145646,268877,0,Revolving loans,F,N,Y,1,135000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
74039,185858,1,Cash loans,M,Y,N,0,157500.0,450000.0,38754.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34126,139539,1,Cash loans,F,N,Y,0,135000.0,942300.0,30528.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26847,131204,0,Revolving loans,F,N,Y,0,90000.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
303571,451722,0,Cash loans,F,Y,Y,1,229500.0,675000.0,32602.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
270755,413865,0,Cash loans,F,N,Y,0,135000.0,302206.5,15561.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
19894,123201,0,Cash loans,M,Y,N,0,360000.0,1418692.5,56394.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
105177,222044,0,Cash loans,M,Y,Y,2,202500.0,450000.0,22018.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,4.0
11473,113358,0,Cash loans,M,Y,Y,0,135000.0,1303812.0,38250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
158608,283875,0,Cash loans,F,Y,Y,0,135000.0,668484.0,19674.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
126829,247085,0,Cash loans,F,Y,N,1,135000.0,269982.0,29205.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
230721,367242,0,Cash loans,F,N,Y,0,247500.0,808650.0,26217.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
83382,196708,0,Revolving loans,XNA,N,Y,1,135000.0,405000.0,20250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
204209,336746,0,Cash loans,M,N,Y,0,135000.0,247675.5,26802.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0
178840,307246,0,Cash loans,M,Y,N,0,135000.0,360000.0,42853.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
125235,245236,0,Cash loans,M,N,Y,1,157500.0,450000.0,21888.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
45070,152210,0,Cash loans,M,Y,N,0,135000.0,621000.0,27481.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
178910,307325,1,Cash loans,F,N,Y,1,76500.0,240660.0,11835.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
12831,114956,0,Cash loans,M,N,N,0,90000.0,172512.0,13959.0,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,4.0
18263,121305,0,Cash loans,F,N,Y,1,121500.0,1046142.0,30717.0,...,0,0,0,0,0.0,0.0,0.0,3.0,0.0,0.0
287354,432855,0,Cash loans,F,N,Y,0,225000.0,1800000.0,47614.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
275522,419299,1,Cash loans,M,Y,Y,0,67500.0,263686.5,14854.5,...,0,0,0,0,0.0,0.0,0.0,1.0,2.0,3.0
179087,307528,0,Cash loans,F,N,Y,0,157500.0,276277.5,12298.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
236029,373387,0,Cash loans,F,N,Y,0,67500.0,675000.0,26410.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4712,105507,0,Cash loans,F,N,Y,0,445500.0,1143000.0,48555.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
292106,438395,1,Cash loans,M,Y,Y,0,180000.0,808650.0,26217.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
253204,392993,0,Cash loans,F,N,Y,0,135000.0,630000.0,20452.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,8.0
205111,337766,0,Cash loans,F,N,Y,0,171000.0,592560.0,28638.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
266836,409140,1,Cash loans,M,N,Y,0,90000.0,450000.0,20979.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
232721,369543,0,Cash loans,F,N,Y,0,90000.0,508495.5,24592.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
108159,225470,0,Revolving loans,M,Y,N,1,405000.0,315000.0,15750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
205250,337924,0,Cash loans,F,N,N,0,247500.0,90000.0,7213.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子